### ISSUE TITLE
pylint_checker doesn't handle from __future__ import unicode_literals

### ISSUE THREAD

**Issue by euresti** [brettcannon/caniusepython3#103]
Sample file:
```
"""Module Docstring"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

def awesome():
    print("awesome")
```

Running `pylint --load-plugins=caniusepython3.pylint_checker --py3k sample.py --report=no` yields the following:
```
************* Module t5
W:  7, 0: native string literal (native-string)
```

**Comment by brettcannon** [comment]
Thanks for the report. I will have a look when I have time. It obviously [should detect it](https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/pylint_checker.py#L95), but that bit of code was tricky to write and obviously I didn't solve it properly.

**Comment by brettcannon** [comment]
I just wanted to give a quick update that I have not forgotten about this. I think I found the issue and have a fix but I need to write a test for it and verify that it works properly.

**Comment by brettcannon** [comment]
https://travis-ci.org/brettcannon/caniusepython3/builds/77944781 verifies this fixes things.

Thanks for the report, David!
