### ISSUE TITLE
numpy already supports Python 3

### ISSUE THREAD

**Issue by chhantyal** [brettcannon/caniusepython3#118]
Numpy already supports Python3. And this CLI was working fine. Recently, something has changed and it gives following output.
```
$ caniusepython3 --projects numpy
Finding and checking dependencies ...
[WARNING] Stale overrides: set([u'reportlab'])

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  numpy
```

Not sure if it is the case with packages that specify version number in PyPi like https://pypi.python.org/pypi/numpy/ gives 404 so we have to use https://pypi.python.org/pypi/numpy/1.8.1

This issue was fist reported here https://github.com/chhantyal/py3readiness/issues/24

**Comment by brettcannon** [comment]
I filed a [bug against PyPI](https://bitbucket.org/pypa/pypi/issues/398/https-pypipythonorg-pypi-numpy-is) since the error is on there end. To temporarily work around it, I have added numpy to the overrides file.
