### ISSUE TITLE
Changes underscore in package names to hyphen

### ISSUE THREAD

**Issue by goelakash** [brettcannon/caniusepython3#122]
I have a package in my requirements.txt called `sphinx_py3doc_enhanced_theme`
But the package that is searched for is sphinx-py3doc-enhanced-theme
```
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/S/sphinx-py3doc-enhanced-theme/project.json: HTTP Error 404: Not Found
```

**Comment by brettcannon** [comment]
This isn't actually a bug with caniusepython3 but with distlib (and it isn't about the name, it's about distlib lacking the metadata). I have commented about this at https://bitbucket.org/pypa/distlib/issues/79/red-dove-metadata-not-being-updated
