### ISSUE TITLE
ProtocolError when calling all_py3_projects

### ISSUE THREAD

**Issue by cfournie** [brettcannon/caniusepython3#150]
pypi.org appears to be pointing to warehouse today, causing calls to `pypi.all_py3_projects()` to throw:
```
ProtocolError: <ProtocolError for pypi.io/pypi: 301 Redirect to Primary Domain>
```

Time to speed up #148?

**Comment by brettcannon** [comment]
I'll try to get this fixed and a new release pushed tomorrow.
