### ISSUE TITLE
nonexistent dependency reported due to erroneous red-dove data used by `distlib`

### ISSUE THREAD

**Issue by johnyf** [brettcannon/caniusepython3#154]
`caniusepython3 --projects omega` reports [`yaclifw`](https://github.com/openmicroscopy/yaclifw) as a dependency of [`omega`](https://github.com/johnyf/omega), but it is not.

The error is due to `distlib` fetching erroneous data from red-dove.com, and has been reported here:
https://bitbucket.org/pypa/distlib/issues/86/red-dove-metadata-misnaming-error
A temporary fix is: https://github.com/johnyf/distlib/commit/597290ddfcb7064051e62a50142ab412122c0d14
In `caniusepython3`, the error originates in [`caniusepython3.dependencies.dependencies`](https://github.com/brettcannon/caniusepython3/blob/0d025e23c5ee25dd26111f26495858b5aa133236/caniusepython3/dependencies.py#L58). A full call trace can be found in the `distlib` issue mentioned above.

The simplest way that I can think of to avoid this situation here is to either:
- instantiate `AggregatingLocator(
                  SimpleScrapingLocator('https://pypi.python.org/simple/',
                                        timeout=3.0),
                  scheme='legacy')` (i.e., omit `JSONLocator`, compared to what `distlib` does), or
- instantiate directly a [`SimpleScrapingLocator`](https://github.com/vsajip/distlib/blob/1d806f5ad38d04c292dd0895016f6f24f9932ca5/distlib/locators.py#L571),

and then call the method `SimpleScrapingLocator.locate` in `caniusepython3.dependencies.dependencies`.

This issue appears thematically in the same area with #126, but it appears to be a different problem.

**Comment by brettcannon** [comment]
Feel free to submit a PR implementing your idea and then we can have a look to see how it affects semantics and the tests.

**Comment by johnyf** [comment]
I plan to submit a PR, but this may take some time before it happens.

**Comment by macleodbroad-wf** [comment]
As per https://bitbucket.org/pypa/distlib/issues/86/red-dove-metadata-misnaming-error this issue has been resolved. I believe we can close this issue.
