### ISSUE TITLE
blocking dependencies not found if dependent says it supports Python 3

### ISSUE THREAD

**Issue by johnyf** [brettcannon/caniusepython3#155]
Two examples:

- `caniusepython3 --projects dd` says that `dd` is ready, because `dd` says so in [its Trove classifiers](https://github.com/johnyf/dd/blob/8113aa95563df13cd2c66f22ccf3aba32dd2b465/setup.py#L45). However, `dd` [depends on](https://github.com/johnyf/dd/blob/8113aa95563df13cd2c66f22ccf3aba32dd2b465/setup.py#L27) `astutils`, which [has forgotten](https://github.com/johnyf/astutils/blob/075e84f6d32e212edc54b80c38163956c6d4b600/setup.py) (me) to declare so with any classifiers. I would expect `caniusepython3` to traverse the entire dependency graph in search for any dependency that cannot be confirmed to be compatible with Python 3. The current behavior seems to truncate the search or the report at the first ancestors that themselves have no Python 3 incompatible ancestors. In this particular case, the truncation happens at the named package, `dd`.

- `caniusepython3 --projects omega` says that `omega` is the only project that needs to transition to Python 3. However, `omega` [depends on `dd`](https://github.com/johnyf/omega/blob/5c1a364b9a596973150f488ecb386d8fda3f2546/setup.py#L24), which depends on `astutils`, which does not declare it is compatible with Python 3. So, the report truncates at `dd`, as above, and `astutils` remains hidden behind it.

For completeness, `caniusepython3 --projects astutils` reports `astutils` to be blocking to itself.

In principle, that a package declares compatibility with Python 3 should be considered as a promise by the package that it has ensured its dependencies work in Python 3 too. But, it doesn't mean that the package has ensured that all its dependencies (ancestors included) are correctly declaring their compatibility with Python 3 using Trove classifiers.

Also, it would be helpful to report the intermediate packages found (i.e., not only those with no Python 3-incompatible ancestors). A package relevant to that purpose is [`pipdeptree`](https://github.com/naiquevin/pipdeptree).

**Comment by brettcannon** [comment]
Could you explain what benefit you would get from having `astutils` reported as not ported? If `dd` says itself is ported then it means you don't have to manually go in and verify whether `astutils` does simply because they don't specify trove classifiers (which a good proportion of projects don't, hence the existence of the [overrides file for caniusepython3](https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/overrides.json)). Beyond completeness, I don't see how changing these semantics will help you as a developer when your direct dependencies claim support.

**Comment by brettcannon** [comment]
Since I never heard back with an explanation as to why this is exactly needed, I'm calling YAGNI and closing this issue.

**Comment by johnyf** [comment]
I apologize for having delayed to react here.

There are two separate cases: whether the package being checked ("top") is the argument given to `caniusepython3` (`dd` in case 1 [above](https://github.com/brettcannon/caniusepython3/issues/155#issue-173385516)) or not:

- if it is, and we add Python 3 to the top package, then none of the dependencies that we wanted to check is ever checked. So, `caniusepython3` would answer "yes" for any package whose `setup.py` we run it on, as long as the package lists Python 3. But the purpose of running `caniusepython3` on a `setup.py` is to start by checking the dependencies, not by starting with the top package's Trove classifiers. So, if truncation happens somewhere, then that should be below the top package, from its descendants and lower.

- if not, then the usefulness I see is in verification of the job that others have done. If listing Python 3 in a package's Trove classifiers on PyPI was possible only if all its immediate dependencies also listed Python 3 in their Trove classifiers, then that would be an inductive invariant on the dependency graph (assumed acyclic) of packages on PyPI.
  
  In that case, yes, I would agree that there is little point in changing the truncation. However, that is not how things work (it could be something for `warehouse` to *require* when uploading a package, but the current implementation of PyPI does not enforce this -- as far as I know). Therefore, I cannot be sure that others (or myself) did remember to check what their dependencies declare.

  So, the benefit is to check properties of the dependency graph that nobody may have bothered to check yet, something that a developer cannot be sure, unless they maintain their entire dependency graph. The overrides file is an explicit way to record deviations from the standard, when those are detected.

  At the very least, a developer who detects such a lack of classifiers can contact the maintainers of the offending package, and note the absent classifiers. In this way, some projects may be reminded to update their classifiers, or perhaps even to re-examine the assumptions they made about their dependencies.

I think that the first case is not what one expects to check with `caniusepython3`. The second case is more on the completeness side, with the benefits noted. If performance is a concern, then a complete check could be made optional, via a command line argument.

**Comment by brettcannon** [comment]
So basically your argument is you don't trust a project's declaration that it supports Python 3 without validating all dependencies also make that declaration? The problem with that is you're going to end up with a ton of false negatives from projects that have not declared Python 3 support but which are implicitly declared by dependent projects. For example, if project A doesn't declare Python 3 support but project B does and has verified things work, then why deal with the false negative result of project A being flagged as not supporting Python 3 when project B has already taken care of that for us implicitly.

This would also place a great burden on this project to make the overrides file comprehensive which would be never-ending. There are too many projects on PyPI which are dormant or make too infrequent of releases to fix their Trove classifiers to make a thorough check succeed without a ton of projects getting added to the overrides file and I simply don't want to deal with that workload.

As for the point of using caniusepython3 on a project that prematurely declared Python 3 support, my answer is to just not prematurely declare Python 3 support. 😉 The Python 3 Trove classifier should simply not be added to a project until support has been reached; classifiers are not aspirational goals but statements about the state of the code.

So while I understand your motivations for wanting a way to perform a more complete check, I still think in the general case it's a YAGNI feature and it will put an undue workload on this project that I don't think is beneficial enough for what it will lead to.

**Comment by johnyf** [comment]
I agree and understand that it is impractical to make this behavior the default. Another possibility would be to offer an option (not the default) for not truncating the search, and reporting the entire graph of dependencies, and their status with respect to Python 3. The description of that option, and possibly a message in the output produced could explicitly declare that:

1. the result does *not* imply that Python 3 cannot be used,
2. no packages that don't declare Python 3 support are reachable directly (i.e., reachable only via packages that declare support), if that has been found to be the case,
3. inconsistencies should not be reported to this project when running in exhaustive mode.

Of course, it still has the potential of triggering a lot of unintended load here.

For premature declaration of Python 3 support by the top package (only---the one that we name as argument), it is simply something that one should not do ("we are all consenting adults here"). I have in mind the enthusiastic developer though, who started porting their project to Python 3, then midway discovered that `caniusepython3` exists, and calls it, but has already modified the Trove classifiers in their package's `setup.py` (because they did so to not forget later). This refers only to the project being checked, not to other projects. It is more about the definition of `caniusepython3`:

- whether it checks all dependencies, vs
- whether it checks the given package (treating itself as a dependency), and then all dependencies.

In other words, it is unclear whether the graph's root is included or not in the definition of what `caniusepython3` does. My understanding was that it checks dependencies, so I was a little surprised to find out that what the top package does matters at all. So, it could be a matter of definition whether to change this behavior or not (simple is better, so uniformly treating the entire graph likely allows for a simpler implementation). It would be helpful though to emphasize somewhere (e.g., in the README) that the top package is included too, and perhaps also at runtime that the search truncated at the top package (which would alarm a developer about prematurely editing the Trove classifiers in their `setup.py`, while preparing for Python 3).

Having said this, one should checkout an earlier commit, and check that, but I would expect this to rarely happen the first time one uses `caniusepython3`.

**Comment by brettcannon** [comment]
I'm willing to accept a PR to clarify the docs that projects passed into caniusepython3 are checked as well just like any other project. I still don't want the added complexity of a more thorough check being added, though.
