### ISSUE TITLE
exit codes for `python setup.py caniusepython3`

### ISSUE THREAD

**Issue by pcattori** [brettcannon/caniusepython3#157]
would be nice if this exited with an non-zero exit code ~~of `1`~~ when a dependency was not python 3 compatible. that way tools like Travis could simply run `python setup.py caniusepython3` and rely on the exit code to determine whether it passed or failed

**Comment by brettcannon** [comment]
I created https://github.com/brettcannon/caniusepython3/blob/master/README_PyPI.rst#integrating-with-your-tests to handle the test integration case originally.

I've [asked on Twitter](https://twitter.com/brettsky/status/778013860838068224) to see what other people think of this change.

**Comment by pcattori** [comment]
the issue I was running into when using the `check` function is that it expects a path to a `requirements.txt` file, whereas I have a `setup.py` file that I want to check. Is there a way to point `check` to a `setup.py` file instead?

**Comment by pcattori** [comment]
for reference: I am basing this behavior on `pylint` which exits with `1` when it runs successfully and finds linting errors.

**Comment by brettcannon** [comment]
No because setup.py is just executable code and not metadata to read. You might be able to assign the result of `setup()` somehow, import your `setup.py` and then inspect for the results (this is why the Python packaging authority are slowly moving away from setup.py files).

**Comment by pcattori** [comment]
I'm interested in finding out more about the alternatives to `setup.py` being considered. Can you point me to a PEP or similar?

**Comment by brettcannon** [comment]
It's all still being developed, so there isn't a set of PEPs to show an end-to-end solution. The start though is https://www.python.org/dev/peps/pep-0518/ . As for tools actively trying to improve things, there's https://pypi.org/project/flit/ and https://pypi.org/project/enscons/ .
