### ISSUE TITLE
`ImportError: No module named backports.functools_lru_cache`

### ISSUE THREAD

**Issue by pcattori** [brettcannon/caniusepython3#159]
When installing directly from github `pip install -e git+https://github.com/brettcannon/caniusepython3#egg=caniusepython3` and running `python setup.py caniusepython3` on python 2.7.12 you get the error above.

Seems that #156 makes use of `backports.functools_lru_cache` but that package is not installed as part of the dependencies. Should probably be added to the `install_requires` section of `setup.py` before the latest version gets published to PyPI :)

**Comment by brettcannon** [comment]
travis was still passing so I suspect a testing dependency was pulling it in. Thanks for the report!
