### ISSUE TITLE
Release new version and fix changelog

### ISSUE THREAD

**Issue by albertyw** [brettcannon/caniusepython3#167]
The changelog for v4.0.0 (https://github.com/brettcannon/caniusepython3#400) says `Return a 3 error code when a command completes successfully but there are found blockers (patch by pcattori)` but the commit for that update isn't included in the v4.0.0 version.  Can you create release another version of caniusepython3 that includes that patch?

**Comment by brettcannon** [comment]
Yeah, sorry about that! Not quite sure how that happened. I will cut a v5.0 with that feature when I have a chance. If you can't wait you can grab the code directly from the repository.

**Comment by albertyw** [comment]
Thanks.  I just added a `-e git://github.com/brettcannon/caniusepython3.git#egg=caniusepython3` in my requirements.txt file.

**Comment by brettcannon** [comment]
Dinner is taking long enough in the oven I was able to push a release out quickly.
