### ISSUE TITLE
biopython and numexpr wrongfully listed as needing transition

### ISSUE THREAD

**Issue by Suor** [brettcannon/caniusepython3#170]
In fact both work on Python 3.

**Comment by brettcannon** [comment]
Both [biopython](https://pypi.org/project/biopython/) and [numexpr](https://pypi.org/project/numexpr/) are listed as unsupported as neither project specified Python 3 support in their trove classifiers on PyPI. Could you submit a PR adding the projects to https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/overrides.json ?

**Comment by brettcannon** [comment]
Fixed by 61024e7081724977f36b769542a3d56aea9f77c4.
