### ISSUE TITLE
intelhex [add to overrides]

### ISSUE THREAD

**Issue by bjarchi** [brettcannon/caniusepython3#180]
intelhex is flagged by the tool as not ported: 

```
You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  intelhex
```

But it's pypi page says otherwise: https://pypi.org/project/IntelHex/

Additionally I have verified that it installs and imports under python3. 

I ran available tests via `python[2,3] -m intelhex.test` and most tests pass under python3. Some tests fail, but these same tests fail under python2 due to missing files. Suspect that either I'm running the test suite wrong or some tests have not been updated as the project changed.

**Comment by brettcannon** [comment]
Any interest in submitting a PR to add IntelHex to the `overrides.json` file?

**Comment by bjarchi** [comment]
Certainly! Not sure if I can get to it today, but probably by the end of the weekend.

**Comment by macleodbroad-wf** [comment]
I believe this has to do with intelhex not explicitly declaring their classifications for python3 support. I've opened a PR to the intelhex repo to add proper classifications: https://github.com/python-intelhex/intelhex/pull/35

**Comment by brettcannon** [comment]
This has been fixed upstream.
