### ISSUE TITLE
slumber not detected as Python 3 compatible

### ISSUE THREAD

**Issue by foobuzz** [brettcannon/caniusepython3#191]
The [slumber](https://pypi.org/project/slumber/) library is compatible with Python 3, and its [setup.py](https://github.com/samgiles/slumber/blob/master/setup.py#L50) includes the Python 3.4 trove classifier. It is, however, flagged as not compatible:

```
$ caniusepython3 --projects slumber
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  slumber
```

**Comment by brettcannon** [comment]
@foobuzz that's because they haven't updated their metadata on PyPI: notice how https://pypi.org/project/slumber/ lacks any list of classifiers in the right-hand column. Would you like to provide a PR to add the project to the overrides.json file?
