### ISSUE TITLE
no support for versioned requirements

### ISSUE THREAD

**Issue by omnilinguist** [brettcannon/caniusepython3#208]
Case in point:
```
$ python ciup3.py -p supervisor
Finding and checking dependencies ...
{'supervisor'}

🎉  You have 0 projects blocking you from using Python 3!

$ python ciup3.py -p supervisor==3.3.1
Finding and checking dependencies ...
{'supervisor==3-3-1'}
[WARNING] problem fetching supervisor==3-3-1, assuming ported (404)

🎉  You have 0 projects blocking you from using Python 3!
```

This is expected based on current behaviour, since https://pypi.org/pypi/supervisor/json shows the 3.7 trove classifier. But it is missing in an older version: https://pypi.org/pypi/supervisor/3.3.1/json

Because of this, projects could be depending on older versions of dependencies that lack py3 support, even though the newest versions do have py3 support, and thus things could get missed at various points in the dependency graph.

Due to the way this system is designed (after an initial inspection of the source), it looks like supporting this might be a somewhat nontrivial enhancement. But, would welcome expert opinion on how feasible this might be?

**Comment by omnilinguist** [comment]
(the `python ciup3.py` construct is a custom hack due to #209)

**Comment by brettcannon** [comment]
It's by design because tracking when support was added at a version level is a lot more work than simply saying the general project has support (e.g. if supervisor had a separate package for support then we would have to track at what version Python 3 support began and that's a good amount of added overhead). So it's doable (and thanks for the idea!), but I don't think it's worth the effort and I'm not up for managing the override metadata for such support.

**Comment by futu** [comment]
According to json output from pypi.org check some version for compatibility is not big deal to implement:

There is version dictionary. Sample output for 2.22.0 version: there is field `  'python_version': 'py2.py3',` and ` 'requires_python': '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',`  for package type: wheel.

` '2.22.0': [
      {
        'comment_text': '',
        'digests': {
          'md5': 'd5327a0023c190febb7e2f491d5ca905',
          'sha256': '9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31'
        },
        'downloads': -1,
        'filename': 'requests-2.22.0-py2.py3-none-any.whl',
        'has_sig': False,
        'md5_digest': 'd5327a0023c190febb7e2f491d5ca905',
        'packagetype': 'bdist_wheel',
        'python_version': 'py2.py3',
        'requires_python': '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
        'size': 57952,
        'upload_time': '2019-05-16T14:37:14',
        'url': 'https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl'
      },
      {
        'comment_text': '',
        'digests': {
          'md5': 'ee28bee2de76e9198fc41e48f3a7dd47',
          'sha256': '11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4'
        },
        'downloads': -1,
        'filename': 'requests-2.22.0.tar.gz',
        'has_sig': False,
        'md5_digest': 'ee28bee2de76e9198fc41e48f3a7dd47',
        'packagetype': 'sdist',
        'python_version': 'source',
        'requires_python': '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
        'size': 113406,
        'upload_time': '2019-05-16T14:37:18',
        'url': 'https://files.pythonhosted.org/packages/01/62/ddcf76d1d19885e8579acb1b1df26a852b03472c0e46d2b959a714c90608/requests-2.22.0.tar.gz'
      }
    ],`


Jsson parsing at this line can be amended:     https://github.com/brettcannon/caniusepython3/blob/916b32b00d79863c0c268b49f49a445dc326eb52/caniusepython3/pypi.py#L89

I can prepare PR for version support.

**Comment by brettcannon** [comment]
I still don't plan to reopen this. As I have no need to care about Python 2 support anymore I am maintaining this as a kindness to the community. As such I don't want to have to support new features at this point. I'm happy to keep the overrides data up-to-date (for now), but having to do PR reviews and deal with potential bugs is not worth it to me.

Now if people want to fork and create their own tools that build on all of this and add more features then please feel free to.
