### ISSUE TITLE
no development instructions

### ISSUE THREAD

**Issue by omnilinguist** [brettcannon/caniusepython3#209]
This is a bit more minor, but I wasn't able to figure out how to test out the command locally, and wasn't able to find any documentation as such. For instance:

```
$ python caniusepython3/__main__.py 
Traceback (most recent call last):
  File "caniusepython3/__main__.py", line 18, in <module>
    from caniusepython3 import dependencies
ModuleNotFoundError: No module named 'caniusepython3'
```

The same error occurs if I try to symlink this file from the project root.

However, a hack that did work was copying `caniusepython3/__main__.py` to say `ciup3.py`, installing some requirements into a venv (eg. `distlib`, `packaging`, `requests`), and then running `python ciup3.py ...` from the project root. Of course, this does mean that if one wants to cut a release, the modified `ciup3.py` would have to be copied back to the original location.

There might be a more proper way that is preferred over this?

**Comment by brettcannon** [comment]
The `__main__.py` file means you can do `python -m caniusepython3` to run the CLI which is the easiest way to run from a source checkout. The other option is doing an editable install with pip if that's your preferred workflow.
