### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by krmaxwell** [brettcannon/caniusepython3#75]
I ran `caniusepython3 -r requirements.txt` against [my requirements.txt](https://github.com/technoskald/maltrieve/blob/master/requirements.txt) and the following error resulted:
``` python
Traceback (most recent call last):
  File "/usr/local/bin/caniusepython3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/caniusepython3/__main__.py", line 159, in main
    check(projects_from_cli(args))
  File "/usr/local/lib/python2.7/dist-packages/caniusepython3/__main__.py", line 86, in projects_from_cli
    projects.extend(projects_from_requirements(parsed.requirements))
  File "/usr/local/lib/python2.7/dist-packages/caniusepython3/__main__.py", line 39, in projects_from_requirements
    for req in reqs:
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 108, in __init__
    self.prereleases = any([is_prerelease(x[1]) and x[0] != "!=" for x in self.req.specs])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 720, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable
```

For context, this is on Python 2.7.6 on Ubuntu 14.04.

**Comment by brettcannon** [comment]
What version of pip do you have installed? And does the file parse fine with `pip install -r requirements.txt` using the latest version of pip? My suspicion is it's pip-specific since I don't do any special processing of requirements files and simply pass the file path on to pip itself.

**Comment by brettcannon** [comment]
I just tried your requirements file, @krmaxwell , and it completed fine for me under Python 2.7.8 with caniusepython3 3.0.0, distlib 0.2.0, pip 6.0.8, and setuptools 12.1. Please check that the dependencies for caniusepython3 are up-to-date. If after the update you are still having issues then please ping this bug and I will reopen it.

**Comment by dellis23** [comment]
This is probably the most random place to put this, but I can't find anywhere else on the internet where others have had this issue.  It took a lot of digging through `pip` and `distlib`'s source.  Hopefully other googlers find this helpful.

This seems to be an issue with installing packages that upgrade `distlib` to a version newer than the installed `pip` library expects.  To fix the issue, I did a `pip uninstall distlib`, followed by `pip install -U pip` to upgrade to the latest version.  Then I was able to install packages as usual.

**Comment by brettcannon** [comment]
Uh, yes, very random. =) You can also always upgrade both pip and distlib simultaneously using ``pip install -U pip distlib`.

**Comment by akimd** [comment]
FWIW, I appear to have a similar problem, using pip install.  I have no idea what's going on.

    Downloading/unpacking ipython[notebook]
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
        url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
      File "/usr/lib/python3/dist-packages/pip/index.py", line 292, in find_requirement
        elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
      File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in is_prerelease
        return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
      File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in <listcomp>
        return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
    TypeError: 'int' object is not iterable

**Comment by brettcannon** [comment]
@akimd That bug is best filed against pip at https://github.com/pypa/pip

**Comment by akimd** [comment]
For the records, it appears to be a Debian only issue.  See the ticket on Pip: https://github.com/pypa/pip/issues/2797 , and then on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786580 .

**Comment by brettcannon** [comment]
Thanks for the links, @akimd !

**Comment by dellis23** [comment]
Did you try my solution @akimd?  That's what I would do if I were me.

**Comment by akimd** [comment]
@dellis23 No, sorry, I have not tried.  My failure appears on a Docker instance, loading a stock Debian machine.  I prefer to wait for Debian to fix their problem that trying to hack the Docker machine.  Thanks!

**Comment by wjdp** [comment]
@dellis23: Googler from the future here, thanks very much!
