### ISSUE TITLE
Outputs `No handlers could be found for logger "ciu"`

### ISSUE THREAD

**Issue by msabramo** [brettcannon/caniusepython3#80]
Note `No handlers could be found for logger "ciu"` in the output below. I haven't yet looked into why it's showing up, but it would be nice if it didn't.

```
$ python setup.py caniusepython3
running caniusepython3
Finding and checking dependencies ...
No handlers could be found for logger "ciu"

You need 3 projects to transition to Python 3.
Of those 3 projects, 2 have no direct dependencies blocking their transition:

  gevent
  paste (which is blocking pastescript)
```

**Comment by brettcannon** [comment]
What version of Python is this under?

**Comment by msabramo** [comment]
2.7

**Comment by msabramo** [comment]
Some more info. It looks like this might only happen with `setup.py caniusepython3` and not with `caniusepython3`, the regular CLI tool.

```
$ caniusepython3 -m profilesvc.egg-info/PKG-INFO
Finding and checking dependencies ...

You have 0 projects blocking you from using Python 3!

$ python setup.py caniusepython3
running caniusepython3
Finding and checking dependencies ...
No handlers could be found for logger "ciu"

You need 5 projects to transition to Python 3.
Of those 5 projects, 4 have no direct dependencies blocking their transition:

  gevent
  nose-testconfig
  paste (which is blocking pastescript)
  wsgiproxy

$ python -V
Python 2.7.9
```

**Comment by msabramo** [comment]
I guess it's because this doesn't get called when you do `setup.py`:

```
$ ag basicConfig
caniusepython3/__main__.py
158:    logging.basicConfig(format='[%(levelname)s] %(message)s')
```

**Comment by paulochf** [comment]
This is happening to me using the cli and Python 2.7.9 .

```
$ caniusepython3 -r requirements.txt
No handlers could be found for logger "ciu"
Finding and checking dependencies ...
[WARNING] Stale overrides: set([u'xlwt', u'jmespath'])
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/B/backports.ssl-match-hostname/project.json: HTTP Error 300: Multiple Choices
Traceback (most recent call last):
  File "/home/paulo/.virtualenvs/data-279-upd/local/lib/python2.7/site-packages/distlib/util.py", line 748, in _get_external_data
    resp = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 300: Multiple Choices
[WARNING] backports.ssl-match-hostname not found
```

There are other errors happening, so you might be interested in them as well.

**Comment by brettcannon** [comment]
Any ideas, @msabramo ?

**Comment by brettcannon** [comment]
@paulochf I can't reproduce the logging issue under Python 2.7 or 3.4. Are you sure you're using v3.1.0 of caniusepython3 with updated dependencies?

**Comment by paulochf** [comment]
Well, I missed something there. I created another env and the `No handlers could be found for logger "ciu"` message is gone.

The rest of the message above still there, so I guess you can split this issue away.

**Comment by phoebebright** [comment]
Have the No handlers could be found for logger "ciu" error after doing a pip install caniusepython3 and running caniusepython3 -r requirements.txt 

This happens on both Unbuntu 14, python 2.7.6 and OSX python 2.7.8

However, appears to be working ok.

**Comment by brettcannon** [comment]
I can't reproduce with a fresh clone of caniusepython3, Python 2.7.10, setuptools 18.2, and pip 7.1.2, @phoebebright . Are you sure you aren't using an old, cached copy of caniusepython3? Otherwise try a clone to see if it still persists.

**Comment by msabramo** [comment]
FWIW, I couldn't reproduce either:

```
$ pip install caniusepython3
...
Successfully installed argparse-1.4.0 caniusepython3-3.2.0 distlib-0.2.1 futures-3.0.3

$ caniusepython3 -r requirements.txt
Finding and checking dependencies ...
[WARNING] Stale overrides: set([u'botocore', u'rsa', u'unicodecsv', u'djangocms-admin-style', u'python-memcached', u'zc.recipe.egg'])

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  pytest-capturelog
```

Python 2.7.9 on OS X

```
$ pip freeze | grep caniusepython3
caniusepython3==3.2.0
```

**Comment by arnuschky** [comment]
```
$ pip freeze | grep caniusepython3
caniusepython3==5.0.0
$ python --version
Python 2.7.12
$ caniusepython3 --requirements requirements/development.txt 
No handlers could be found for logger "ciu"
Finding and checking dependencies ...
```
Ubuntu 16.04 64bit

**Comment by brettcannon** [comment]
@arnuschky if you add `logging.basicConfig()` right after `import logging`, does that fix and still lead to the expected output?

**Comment by arnuschky** [comment]
Yes that works. (I added it in `__main__.py`)

It hides the warning but leads to the following output:
```
WARNING:ciu:A requirement lacks a name (e.g. no `#egg` on a `file:` path)
WARNING:ciu:A requirement lacks a name (e.g. no `#egg` on a `file:` path)
```

This prettifies it a bit:
`logging.basicConfig(format='%(levelname)s: %(message)s')`

**Comment by brettcannon** [comment]
@arnuschky There's actually already a call like that to `logging.basicConfig()` at https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/__main__.py#L163, but it probably should just be done at the global level.

Any interest is proposing a PR to fix this?
