### ISSUE TITLE
TypeError thrown when looking at all pypi projects.

### ISSUE THREAD

**Issue by rawrgulmuffins** [brettcannon/caniusepython3#87]
While running a very simple but long running program I received this stack.

Program Code:

    from collections import Counter
    from pprint import pprint

    import caniusepython3
    from caniusepython3.dependencies import blocking_dependencies

    all_py_projects = list(caniusepython3.pypi.all_projects())
    py3_projects = caniusepython3.pypi.all_py3_projects()
    all_blockers = blocking_dependencies(
        all_py_projects,
        py3_projects)
    blocker_list = []
    for blockers_subset in all_blockers:
        for blocker in blockers_subset:
            blocker_list.append(blocker)
    blockers_counter = Counter(blocker_list)
    pprint(blockers_counter.most_common())

Just as a warning this takes my poor laptop a couple hours to run.

Stack

    Traceback (most recent call last):
      File "top_python3_blockers.py", line 15, in <module>
        py3_projects)
      File "/Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-packages/caniusepython3-3.1.0-py3.4.egg/caniusepython3/dependencies.py", line 98, in blocking_dependencies
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
        yield future.result()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 395, in result
        return self.__get_result()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
        raise self._exception
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-packages/caniusepython3-3.1.0-py3.4.egg/caniusepython3/dependencies.py", line 60, in dependencies
      File "/Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-packages/distlib/database.py", line 375, in run_requires
        return self._get_requirements('run_requires')
      File "/Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-packages/distlib/database.py", line 371, in _get_requirements
        env=self.context))
      File "/Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-packages/distlib/metadata.py", line 874, in get_requirements
        result.extend(d['requires'])
    TypeError: string indices must be integers

I'm going to re-run the sample code using `python  -m pdb` to see if I can figure out what's happening.

**Comment by brettcannon** [comment]
Looks like a distlib bug where `d` is being set to a string instead of a dict.

**Comment by rawrgulmuffins** [comment]
# Repro code on python 3.4
from distlib.database import Metadata
meta_data = Metadata()
meta_data.get_requirements(['uttt'], set()) # Valid pypi package, ultimate tick tack toe =P

# Next steps that I see

* Check if the bug is present in distlib.2.2_dev
* Report the bug to distlib if present
* create a try, except that wraps line 60 in caniusepython3.dependencies.dependencies 

I wasn't able to get a breakpoint to work in get_requirements so I don't really understand what's happening at this point 

    (Pdb) import distlib.metadata
    (Pdb) b distlib.metadata.Metadata.get_requirements
    Breakpoint 7 at /Users/alexlord/.virtualenvs/porting_authority/lib/python3.4/site-    packages/distlib/metadata.py:844
    (Pdb) meta_data.get_requirements(['uttt'], set())
    *** TypeError: string indices must be integers

# get_requirements source

    def get_requirements(self, reqts, extras=None, env=None):
        """
        Base method to get dependencies, given a set of extras
        to satisfy and an optional environment context.
        :param reqts: A list of sometimes-wanted dependencies,
                      perhaps dependent on extras and environment.
        :param extras: A list of optional components being requested.
        :param env: An optional environment for marker evaluation.
        """
        if self._legacy:
            result = reqts
        else:
            result = []
            extras = get_extras(extras or [], self.extras)
            for d in reqts:
                if 'extra' not in d and 'environment' not in d:
                    # unconditional
                    include = True
                else:
                    if 'extra' not in d:
                        # Not extra-dependent - only environment-dependent
                        include = True
                    else:
                        include = d.get('extra') in extras
                    if include:
                        # Not excluded because of extras, check environment
                        marker = d.get('environment')
                        if marker:
                            include = interpret(marker, env)
                if include:
                    result.extend(d['requires'])
            for key in ('build', 'dev', 'test'):
                e = ':%s:' % key
                if e in extras:
                    extras.remove(e)
                    # A recursive call, but it should terminate since 'test'
                    # has been removed from the extras
                    reqts = self._data.get('%s_requires' % key, [])
                    result.extend(self.get_requirements(reqts, extras=extras,
                                                        env=env))
        return result

**Comment by rawrgulmuffins** [comment]
Seems like my repro isn't actually a repro. =(

https://bitbucket.org/pypa/distlib/issue/73/distlibdatabasemetadataget_requirements

**Comment by vsajip** [comment]
The problem might be due to bad dependency metadata for some distribution. I would suggest enabling logging and seeing for which distribution the original failure occurred. Link to an updated script is [here](https://gist.github.com/vsajip/03e9fc99bceec3e5b1cf).
